baseURL: "https://folorunshoayomide.com"
languageCode: "en-us"
title: "Hugo Profile"
theme: hugo-profile

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "My Hugo Website"
  description: "Text about my cool site"
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Folorunsho Ayomide ."
    subtitle: "I build web applications "
    content: "A passionate web developer and also an upcoming blockchain developer ."
    image: /avi.png
    button:
      enable: true
      name: "Resume"
      url: "/FOLORUNSHO AYOMIDE RESUME.pdf"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/deen257
        - icon: fab fa-twitter
          url: https://twitter.com/Ayomid_
        - icon: fab fa-github
          url: https://www.linkedin.com/in/folorunsho-ayomide-2369441b5/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/avi.png"
    content: |-
      I am a passionate developer dedicated to building web application from the ground up. I’m interested in blockchain technology and development.
      I'm currently learning learning React, Next and other frameworks.
      I'm looking to collaborate on full stack projects and Ethereum development projects.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "Pyhton"
        - "Node"
        - "Flask"

  # Experience
#   ---
#    experience:
#     enable: true
#     items:
#       - job: "JOB TITLE 1"
#         company: "COMPANY NAME"
#         companyUrl: "https://example.com"
#         date: ""
#         featuredLink:
#           enable: true
#           url: "https://example.com"
#         info:
#           enable: true
#           content: Job description
#           I am currently working as a  developer at [example org.](https://example.com) in ...., . I am currently working on a project that ...
#           - Job duties.
#           - Job duties.
#
#       - job: "JOB TITLE 2"
#         company: "COMPANY NAME"
#         companyUrl: "https://example.com"
#         date: ""
#         featuredLink:
#           enable: true
#           url: "https://example.com"
#         info:
#           enable: true
#           content: Job description
#           I am currently working as a  developer at [example org.](https://example.com) in ...., . I am currently working on a project that ...
#           - Job duties.
#           - Job duties.

# ---
  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Udacity Full-stack Nanodegree "
        school:
          name: "Udacity"
          url: "https://www.linkedin.com/in/folorunsho-ayomide-2369441b5/"
        date: "Mar.2022 - Jul. 2022"
        GPA: "Distinction"
        
      - title: "Bachelor of Engineering "
        school:
          name: "Univerity of Ilorin, Nigeria"
          url: "https://folorunshoayomide.com"
        date: "IN VIEW"
        # GPA: ""
        # ----
        # content:
        #     - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        #     - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        #
        #   featuredLink:
        #     enable: true
        #     name: "My academic record"
        #     url: "https://example.com"
        # 
        # ---

  # Achievements
  # ---
  # achievements:
  #   enable: true
  #   items:
  #     - title: Acheivement title 
  #       content: ...
  #       url: https://example.com
  #     - title: Acheivement title 2
  #       content: ...
  #     
  # ---

  # projects
  projects:
    enable: true
    items:
      - title: My Hugo Website Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /profile.png
        featured:
          name: Demo
          link: https://github.com/deen257
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          
      - title: Flask API to a Kubernetes cluster
        content: Utilizing Docker and AWS for server deployment, containerization and testing
        image: /Flaskapi.png
        featured:
          name: Demo
          link: https://github.com/deen257/cd0157-Server-Deployment-and-Containerization
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/deen257/cd0157-Server-Deployment-and-Containerization


  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: Folorunshoayomide@46gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/deen257
      linkedin: https://www.linkedin.com/in/folorunsho-ayomide-2369441b5/
      twitter: https://twitter.com/Ayomid_
      instagram: https://www.instagram.com/ayomid_/
